name: Monitoramento de Sites

on:
  schedule:
    - cron: "*/30 * * * *"  # A cada 30 minutos
  workflow_dispatch:       # Permite rodar manualmente também

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar verificação
        run: python monitor.py
